export const INIT_LOGIN='INIT_LOGIN'
export const INIT_LOGIN_SUCCESS='INIT_LOGIN_SUCCESS'
export const INIT_LOGIN_FAIL='INIT_LOGIN_FAIL'
export const CLEAR_ALL='CLEAR_ALL'



export const VERIFY_USER='VERIFY_USER'
export const VERIFY_USER_SUCCESS='VERIFY_USER_SUCCESS'
export const VERIFY_USER_FAIL='VERIFY_USER_FAIL'